name: C/C++ CI

on: [push]

jobs:
  # build:

    # runs-on: ubuntu-latest

    # steps:
    # - uses: actions/checkout@v1
    # - name: ex_so1
    #   run: make ex_so1
    # - name: ex_so_rastrigin
    #   run: make ex_so_rastrigin
    # - name: ex_so_bind
    #   run: make ex_so_bind
    # - name: ex_mo1
    #   run: make ex_mo1
    # - name: ex_mo_dtlz2
    #   run: make ex_mo_dtlz2
    # - name: ex_init_solutions
    #   run: make ex_init_solutions

    # - name: CI skim test single-objective 
    #   run: cd ci-test-cases && make so-skim
    # - name: CI skim test multi-objective 
    #   run: cd ci-test-cases && make mo-skim

    # - name: CI address sanitizer test single-objective 
    #   run: cd ci-test-cases && make so-sanitizer-address
    # - name: CI address sanitizer test multi-objective 
    #   run: cd ci-test-cases && make mo-sanitizer-address

    # - name: CI thread sanitizer test single-objective 
    #   run: cd ci-test-cases && make so-sanitizer-thread
    # - name: CI thread sanitizer test multi-objective 
    #   run: cd ci-test-cases && make mo-sanitizer-thread

    # - name: CI UB sanitizer test single-objective 
    #   run: cd ci-test-cases && make so-sanitizer-ub
    # - name: CI UB sanitizer test multi-objective 
    #   run: cd ci-test-cases && make mo-sanitizer-ub

    # - name: CI clang compatibility check single-objective 
    #   run: cd ci-test-cases && make so-clang
    # - name: CI clang compatibility check multi-objective 
    #   run: cd ci-test-cases && make mo-clang

  windows-compatibility:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v1
    - name: mkdir
      run:
        cmd.exe /C mkdir include
    - name: dir include directory
      run:
        cmd.exe /C dir "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\SDK\ScopeCppSDK\vc15\VC\include\*" include
    - name: copy include directory 1
      run:
        cmd.exe /C xcopy /E "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\SDK\ScopeCppSDK\vc15\VC\include\*" include
    - name: copy include directory 2
      run:
        cmd.exe /C xcopy /E "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\SDK\ScopeCppSDK\vc15\SDK\include\*" include
    # - name: copy cl.exe
    #   run:
    #     cmd.exe /C copy "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\SDK\ScopeCppSDK\vc15\VC\bin\cl.exe" .
    # - name: copy clui.dll
    #   run:
    #     cmd.exe /C copy "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\SDK\ScopeCppSDK\vc15\VC\bin\1033\clui.dll" .
    - name: copy bin
      run:
        cmd.exe /C xcopy /E "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\SDK\ScopeCppSDK\vc15\VC\bin\*" .
    - name: tree
      run:
        cmd.exe /C tree /F /A
    - name: run cl.exe
      run:
        cmd.exe /C cl.exe /std:c++latest /I ..\src /I .\include /I .\include\ucrt examples/so-1/example_so1.cpp
        # cmd.exe /c '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\SDK\ScopeCppSDK\vc15\VC\bin\cl.exe" /std:c++latest /I ../src /I "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\SDK\ScopeCppSDK\vc15\VC\include\" examples/so-1/example_so1.cpp'
        # cmd.exe /c "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\Tools\VsDevCmd.bat" "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\SDK\ScopeCppSDK\vc15\VC\bin\cl.exe" /std:c++latest /I ../src /I "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\SDK\ScopeCppSDK\vc15\VC\include\" examples/so-1/example_so1.cpp
        # cmd.exe /c powershell.exe "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" ; "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\SDK\ScopeCppSDK\vc15\VC\bin\cl.exe" /std:c++latest /I ../src /I "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\SDK\ScopeCppSDK\vc15\VC\include\" examples/so-1/example_so1.cpp
        # C:\WINDOWS\system32\WindowsPowerShell\v1.0\powershell.exe  -Command "\"C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat\" ; \"C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\SDK\ScopeCppSDK\vc15\VC\bin\cl.exe\" /std:c++latest /I ../src /I 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\SDK\ScopeCppSDK\vc15\VC\include\' examples/so-1/example_so1.cpp"

  rem-test0:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v1
    - name: CI msbuild compatibility check single-objective 
      run: |
        cmd.exe /C 'python.exe aaa.py'
        # cmd.exe /C dir 'C:\Program Files (x86)\'
        # cmd.exe /C powershell.exe "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\SDK\ScopeCppSDK\vc15\VC\bin\cl.exe" /std:c++latest /I ../src /I "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\SDK\ScopeCppSDK\vc15\VC\include\" examples\so-1\example_so1.cpp
        # cmd.exe /C 'python.exe --version'
        # cmd.exe /C 'dir "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\SDK\ScopeCppSDK\vc15\SDK\include"'
        # cmd.exe /C '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"'
        # cmd.exe /C '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\SDK\ScopeCppSDK\vc15\VC\bin\cl.exe" /std:c++latest /Yc"stdafx.pch" /Yu"stdafx.h" /FI"stdafx.h" /I ../src examples/so-1/example_so1.cpp'
        # cmd.exe /C '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\SDK\ScopeCppSDK\vc15\VC\bin\cl.exe" /std:c++latest /Yu"stdafx.h" /FI"stdafx.h" /I ../src examples/so-1/example_so1.cpp'
        # cmd.exe /C '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\SDK\ScopeCppSDK\vc15\VC\bin\cl.exe" /std:c++latest /Yc"stdafx.h" /FI"stdafx.h" /I ../src examples/so-1/example_so1.cpp'
        # cmd.exe /C '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\SDK\ScopeCppSDK\vc15\VC\bin\cl.exe" /std:c++latest /Yc"stdafx.pch" /Yu"stdafx.h" /FI"stdafx.h" /I ../src examples/so-1/example_so1.cpp'
    - name: CI msbuild compatibility check multi-objective 
      run: |
        "c:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\msbuild.exe" examples/mo-1/example_mo1.cpp /std:latest /I ../src

  rem-test1:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v1
    - name: vcvarsall
      run:
        cmd.exe /C "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
    - name: devenv
      run:
        devenv project.sln /Command "File.OpenFile examples/so-1/example_so1.cpp" /Command "Build.Compile" /Command "File.Exit"
        # cmd.exe /C dir "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\SDK\ScopeCppSDK\vc15\VC\include\*" include
